"""
llm_hint.py
===========
Aggregate per-program stats from a baseline trace JSON, call Solar Pro 3
for priority recommendations, and write an xv6-readable hints.txt.

Usage:
    python3 llm_hint.py <baseline_trace.json> [--output hints.txt]

If the API key is missing, falls back to a deterministic heuristic so
you can still test the pipeline offline.
"""

import argparse
import json
import os
import sys
from collections import defaultdict
from pathlib import Path

from dotenv import load_dotenv
from openai import OpenAI

# Local import — ensure prompts.py is in the same dir
from prompts import PRIORITY_RECOMMENDATION_PROMPT_FEWSHOT


# Programs we never want to "advise" — they're framework processes,
# not part of the workload under analysis.
SKIP_NAMES = {"wrunner", "nlrun", "sh", "init"}


def aggregate(trace: dict) -> dict:
    """Per-program-name averaged stats from EXIT events."""
    by_name = defaultdict(list)
    for e in trace["events"]:
        if e["kind"] != "exit":
            continue
        if e["name"] in SKIP_NAMES:
            continue
        by_name[e["name"]].append(e)

    stats = {}
    for name, evts in by_name.items():
        n = len(evts)
        avg_run = sum(e["run"] for e in evts) / n
        avg_io = sum(e["ioblock"] for e in evts) / n
        stats[name] = {
            "run_ticks": round(avg_run, 1),
            "io_blocks": round(avg_io, 1),
            "n_instances": n,
        }
    return stats


def heuristic_hints(stats: dict) -> dict:
    """Used when API key is absent."""
    out = {}
    for name, s in stats.items():
        run, io = s["run_ticks"], s["io_blocks"]
        if io > max(run / 4.0, 5):
            out[name] = 0
        elif io < 2:
            out[name] = 2
        else:
            out[name] = 1
    return out


def call_llm(stats: dict) -> dict:
    load_dotenv()
    key = os.getenv("UPSTAGE_API_KEY")
    base = os.getenv("UPSTAGE_BASE_URL", "https://api.upstage.ai/v1")
    model = os.getenv("UPSTAGE_MODEL", "solar-pro3")
    effort = os.getenv("UPSTAGE_REASONING_EFFORT", "low")

    if not key or key == "your_api_key_here":
        print("[llm] no API key, using heuristic fallback", file=sys.stderr)
        return heuristic_hints(stats)

    client = OpenAI(api_key=key, base_url=base)
    prompt = PRIORITY_RECOMMENDATION_PROMPT_FEWSHOT.format(
        stats_json=json.dumps(stats, indent=2)
    )
    print(f"[llm] querying {model} (effort={effort})...", file=sys.stderr)

    try:
        resp = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.0,
            max_tokens=1024,
            extra_body={"reasoning_effort": effort},
        )
        text = resp.choices[0].message.content.strip()
        if text.startswith("```"):
            text = text.strip("`")
            if text.lower().startswith("json"):
                text = text[4:].strip()
        parsed = json.loads(text)

        cleaned = {}
        for k, v in parsed.items():
            try:
                iv = int(v)
            except (ValueError, TypeError):
                print(f"[llm] bad value for {k}: {v!r}, default to 1",
                      file=sys.stderr)
                iv = 1
            if iv not in (0, 1, 2):
                print(f"[llm] invalid level {iv} for {k}, clamp to 1",
                      file=sys.stderr)
                iv = 1
            cleaned[k] = iv
        return cleaned

    except Exception as e:
        print(f"[llm] call/parse failed ({type(e).__name__}: {e})",
              file=sys.stderr)
        print("[llm] falling back to heuristic", file=sys.stderr)
        return heuristic_hints(stats)


def write_hints_file(hints: dict, out_path: Path):
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        f.write("# Generated by llm_hint.py\n")
        f.write("# format: <program_name> <level>   (0=HIGH 1=MID 2=LOW)\n")
        for name, lvl in hints.items():
            f.write(f"{name} {lvl}\n")
    print(f"[llm] wrote {out_path}", file=sys.stderr)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("trace_json", help="baseline trace JSON from parse_trace.py")
    ap.add_argument("--output", default="hints.txt")
    args = ap.parse_args()

    with open(args.trace_json) as f:
        trace = json.load(f)

    stats = aggregate(trace)
    print(f"[llm] aggregated stats for {len(stats)} program(s):", file=sys.stderr)
    for name, s in stats.items():
        print(f"  {name}: run_ticks={s['run_ticks']:.1f} "
              f"io_blocks={s['io_blocks']:.1f} (n={s['n_instances']})",
              file=sys.stderr)

    if not stats:
        print("[llm] no programs to advise on (only skip-names found)",
              file=sys.stderr)
        return 1

    hints = call_llm(stats)
    print(f"[llm] hints: {hints}", file=sys.stderr)

    write_hints_file(hints, Path(args.output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
