#!/usr/bin/perl -w

# Smart-MLFQ-xv6 modified usys.pl
# ==============================
# Added: setpri, getstats, settrace, forkpri

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $prefix = "sys_";
    my $name = shift;
    if ($name eq "sbrk") {
	print ".global $prefix$name\n";
	print "$prefix$name:\n";
    } else {
	print ".global $name\n";
	print "$name:\n";
    }
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}

entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("pause");
entry("uptime");
entry("setpri");    # Smart-MLFQ
entry("getstats");  # Smart-MLFQ
entry("settrace");  # Smart-MLFQ (I2)
entry("forkpri");   # Smart-MLFQ (I4)
# === minju: 시스템콜 추적 ===
entry("trace_on");
entry("trace_off");
entry("trace_stats");
# === jinhwan: thread / futex ===
entry("thread_create");
entry("thread_join");
entry("thread_exit");
entry("futex_wait");
entry("futex_wake");
# === haneol: process listing ===
entry("ps");
entry("sysinfo");
